# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CD dev

on:
  push:
    branches: [ "development" ]
    
jobs:
 build:
    name: Deploy to VPS Dev
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/wahyu/ci_cd_node_belajar
          git pull origin development
          git status
          export PATH="/root/.nvm/versions/node/v16.14.0/bin:$PATH"
          echo "PATH: $PATH"
          npm i --only=prod
          pm2 restart cicd_node
